[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
	call unite#custom#default_action('directory', 'vimfiler')

	nnoremap [unite] :Unite
	nmap ,u [unite]
	" バッファ一覧
	nnoremap <silent> [unite]b :<C-u>Unite buffer<CR>
	" ファイル一覧
	nnoremap <silent> [unite]f :<C-u>Unite file_rec<CR>
	" ディレクトリ一覧
	nnoremap <silent> [unite]s :<C-u>Unite directory<CR>
	" bookmark
	nnoremap <silent> [unite]j :<C-u>Unite bookmark<CR>
	" 最近使用したファイル一覧(ファイル・ディレクトリ)
	nnoremap <silent> [unite]m :<C-u>Unite file_mru directory_mru<CR>
	" 最近使用したファイル一覧(ディレクトリ・ファイル)
	nnoremap <silent> [unite]d :<C-u>Unite directory_mru file_mru<CR>
	" カラースキーマ(プレビュー)
	nnoremap <silent> ,cs :<C-u>Unite colorscheme -auto-preview<CR>
'''

# Python3 に依存
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
	call denite#custom#option('default', 'direction', 'top')
	" 上下移動を<C-N>, <C-P>
	call denite#custom#map('normal', '<C-N>', '<denite:move_to_next_line>')
	call denite#custom#map('normal', '<C-P>', '<denite:move_to_previous_line>')
	call denite#custom#map('insert', '<C-N>', '<denite:move_to_next_line>')
	call denite#custom#map('insert', '<C-P>', '<denite:move_to_previous_line>')
	" タブオープンを<C-T>
	call denite#custom#map('insert', '<C-T>', '<denite:do_action:tabopen>')
	" 部分一致(スペースで複数可)
	call denite#custom#source('file_mru', 'matchers', ['matcher_substring'])

	nnoremap [denite] :Denite
	nmap ,d [denite]
	" ファイル一覧
	nnoremap <silent> ,fr :<C-u>Denite file_rec<CR>
	" ディレクトリ一覧
	nnoremap <silent> ,dr :<C-u>Denite directory_rec<CR>
	" 最近使用したファイル一覧(ファイル・ディレクトリ)
	nnoremap <silent> ,fm :<C-u>Denite file_mru directory_mru<CR>
	" 最近使用したファイル一覧(ディレクトリ・ファイル)
	nnoremap <silent> ,dm :<C-u>Denite directory_mru file_mru<CR>
	" grep
	nnoremap <silent> ,gr :<C-u>Denite grep -auto-preview<CR>
	nnoremap <silent> ,gc :<C-u>DeniteCursorWord grep -auto-preview<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
	call vimfiler#custom#profile('default', 'context', {
\		'auto_cd': 1,
\		'safe': 0,
\		'fnamewidth': 74,
\		'sort_type': 'Time',
\	})

	nnoremap [vimfiler] :VimFiler
	nmap ,f [vimfiler]
	" VimFiler(バッファディレクトリ)
	nnoremap <silent> [vimfiler]d :<C-u>VimFilerBufferDir<CR>
	" VimFiler(カレントディレクトリ)
	nnoremap <silent> [vimfiler]c :<C-u>VimFilerCurrentDir<CR>
'''

[[plugins]]
repo = 'thinca/vim-singleton'
hook_source = '''
	call singleton#enable()
'''

[[plugins]]
repo = 'mattn/webapi-vim'
[[plugins]]
repo = 'mattn/wwwrenderer-vim'

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = '''
	let g:ref_source_webdict_cmd = '=wwwrenderer#render("%s")'
	let g:ref_source_webdict_use_cache = 1

	let g:ref_source_webdict_sites = {
\		'je': {
\			'url': 'http://dictionary.infoseek.ne.jp/jeword/%s',
\		},
\		'ej': {
\			'url': 'http://dictionary.infoseek.ne.jp/ejword/%s',
\		},
\	}

	function! g:ref_source_webdict_sites.je.filter(output)
		return join(split(a:output, "\n")[25 :], "\n")
	endfunction

	function! g:ref_source_webdict_sites.ej.filter(output)
		return join(split(a:output, "\n")[25 :], "\n")
	endfunction

	" 辞書(Webを使用)
	nnoremap ,dw :<C-u>Ref webdict 
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
	let g:rooter_use_lcd = 0
	let g:rooter_patterns = ['GTAGS', '.git/', '.svn/', '.root/']
'''

[[plugins]]
repo = 'fuenor/qfixhowm'
hook_add = '''
	let g:QFix_Height = 6
	let g:QFix_PreviewHeight = 24
	let g:QFixHowm_Key = ','
	let g:QFixHowm_KeyB = 'h'
	let g:QFixHowm_CalendarWinCmd = 'vertical botright'
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
\		'active': {
\			'left': [
\				['mode', 'paste'],
\				['readonly', 'filename', 'modified', 'ale'],
\			]
\		},
\		'component_function': {
\			'ale': 'ALEGetStatusLine'
\		}
\	}
'''

[[plugins]]
repo = 'kana/vim-altr.git'
hook_add = '''
	" ヘッダファイルとソースファイルを切り替える
	command! A call altr#forward()
'''

[[plugins]]
repo = 'sheerun/vim-wombat-scheme'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/DirDiff.vim'

[[plugins]]
repo = 'vim-scripts/copypath.vim'

[[plugins]]
repo = 'vim-scripts/BlockDiff'
