[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'thinca/vim-singleton'
hook_source = '''
	call singleton#enable()
'''

[[plugins]]
repo = 'mattn/webapi-vim'
[[plugins]]
repo = 'mattn/wwwrenderer-vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
hook_add = '''
	let g:neomru#file_mru_limit = 1000000
	let g:neomru#directory_mru_limit = 1000000
'''

#[[plugins]]
#repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
	let g:rooter_targets = '*'
	let g:rooter_use_lcd = 1
	let g:rooter_patterns = ['GTAGS', 'Makefile', '.git/', '.svn/', '.root/']
'''

[[plugins]]
repo = 'fuenor/qfixhowm'
hook_add = '''
	let g:QFix_Height = 6
	let g:QFix_PreviewHeight = 24
	let g:QFixHowm_Key = ','
	let g:QFixHowm_KeyB = 'h'
	let g:QFixHowm_CalendarWinCmd = 'vertical botright'
	" ripgrepを使う（PATHは通してある前提）
	let g:mygrepprg='rg'
	" 実行時のオプションをripgrep用に変更（GNU Grepと同じ出力になるように）
	let g:MyGrepcmd_useropt='-nH --no-heading --color never'
	let g:MyGrepcmd_regexp=''
	let g:MyGrepcmd_regexp_ignore='-i'
	let g:MyGrepcmd_fix='-F'
	let g:MyGrepcmd_fix_ignore='-F -i'
	let g:MyGrepcmd_recursive=''
	" gipgrepにファイルパターンとして「*」「*.*」を渡したらエラーになったのでその対策
	let g:MyGrep_GrepFilePattern='.'
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'sheerun/vim-wombat-scheme'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'rhysd/neovim-component'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

# ultisnips, YouCompleteMeで必要
[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = '0'
rev = 'release'

[[plugins]]
repo = 'TopconTokyo/cpp-deprecated.vim'

